var INTSYS = INTSYS || {};

INTSYS.CONS =  {
	LABEL_COLORS: ['#676767', '#9b9b9b', '#B9B9B9'],
	RECOMMENDATION_COLOR: '#ca00ca',
	PREFERENCE_COLOR: '#1db954',
	SELECTED_COLOR: '#fefefe',
	BACKGROUND_COLOR: '#212121',
	LOG_TYPE_SYSTEM_INFO: 'SYSTEM_INFO',
	LOG_TYPE_USER_INFO: 'USER_INFO',
	LOG_TYPE_RECOMMENDATION_VIEW_CLICK: 'CLICK_RECOMMENDATION_VIEW',
	LOG_TYPE_PLAYLIST_VIEW_CLICK: 'CLICK_PLAYLIST_VIEW',
	LOG_TYPE_DETAILS_VIEW_CLICK: 'CLICK_DETAILS_VIEW',
	LOG_TYPE_MAIN_VIEW_CLICK: 'CLICK_MAIN_VIEW',
	LOG_TYPE_MAIN_VIEW_SCROLL: 'SCROLL_MAIN_VIEW',
	LOG_TYPE_ZOOM_IN: 'ZOOM_IN',
	LOG_TYPE_ZOOM_OUT: 'ZOOM_OUT',
	LOG_TYPE_ZOOM_VIA_BUTTON: 'ZOOM_VIA_BUTTON',
	LOG_TYPE_MINIMAP_CLICK: 'MINIMAP_CLICK'
}